// user actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE"

export const LOGOUT = "LOGOUT"

// budget action
export const GET_MONTHLY_BUDGET_OVERVIEW_LOADING = "GET_MONTHLY_BUDGET_OVERVIEW_LOADING"
export const GET_MONTHLY_BUDGET_OVERVIEW_SUCCESS = "GET_MONTHLY_BUDGET_OVERVIEW_SUCCESS"
export const GET_MONTHLY_BUDGET_OVERVIEW_FAILURE = "GET_MONTHLY_BUDGET_OVERVIEW_FAILURE"