// user actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE"

export const LOGOUT = "LOGOUT"

// budget action
export const GET_MONTHLY_BUDGET_OVERVIEW_LOADING = "GET_MONTHLY_BUDGET_OVERVIEW_LOADING"
export const GET_MONTHLY_BUDGET_OVERVIEW_SUCCESS = "GET_MONTHLY_BUDGET_OVERVIEW_SUCCESS"
export const GET_MONTHLY_BUDGET_OVERVIEW_FAILURE = "GET_MONTHLY_BUDGET_OVERVIEW_FAILURE"

export const ADD_BUDGET_ITEMS_REQUEST = "ADD_BUDGET_ITEMS_REQUEST"
export const ADD_BUDGET_ITEMS_SUCCESS = "ADD_BUDGET_ITEMS_SUCCESS"
export const ADD_BUDGET_ITEMS_FAILURE = "ADD_BUDGET_ITEMS_FAILURE"

// budget types action
export const GET_BUDGET_TYPES_LOADING = "GET_BUDGET_TYPES_LOADING"
export const GET_BUDGET_TYPES_SUCCESS = "GET_BUDGET_TYPES_SUCCESS"
export const GET_BUDGET_TYPES_FAILURE = "GET_BUDGET_TYPES_FAILURE"

// category action
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE"